auto: false
server: false
lsi: false
markdown: rdiscount
pygments: true
permalink: /:title
paginate: 10
category_dir: topics
category_title_prefix: 
exclude: ["lib", "blog.rb", "Capfile", "config", "log", "Rakefile", "tmp"]
destination: public